declare let timeRemaining: number;
declare let maxTime: number;
declare let taps: number;
declare let score: number;
declare let isRunning: boolean;
declare let lastFrameTime: number;
declare let ringColor: string;
declare let lives: number;
declare let isReadySetGo: boolean;
declare let isShrinking: boolean;
declare let streak: number;
declare let perfects: number;
declare let greats: number;
declare let goods: number;
declare let fines: number;
declare let poors: number;
declare let bads: number;
declare let perfectPoints: number;
declare let greatPoints: number;
declare let goodPoints: number;
declare let finePoints: number;
declare let poorPoints: number;
declare let badPoints: number;
declare const POINTS: {
    perfect: number;
    great: number;
    good: number;
    fine: number;
    poor: number;
    bad: number;
};
declare let currentInitials: string[];
declare let deviceType: 'desktop' | 'mobile';
declare let userId: string;
declare const instructionsPopup: HTMLElement;
declare const mainMenuScreen: HTMLElement;
declare const startScreen: HTMLElement;
declare const gameplayScreen: HTMLElement;
declare const gameoverScreen: HTMLElement;
declare const scoreScreen: HTMLElement;
declare const leaderboardScreen: HTMLElement;
declare const gotItButton: HTMLElement;
declare const startGameButton: HTMLElement;
declare const helpButton: HTMLElement;
declare const leaderboardButton: HTMLElement;
declare const startTimerRing: HTMLElement;
declare const startHearts: HTMLElement;
declare const startInstruction: HTMLElement;
declare const timerDisplay: HTMLElement;
declare const scoreDisplay: HTMLElement;
declare const timerRing: HTMLElement;
declare const gameplayHearts: HTMLElement;
declare const instruction: HTMLElement;
declare const countdown: HTMLElement;
declare const tierScoreboard: HTMLElement;
declare const timerContainer: HTMLElement;
declare const maxDisplay: HTMLElement;
declare const lifeLost: HTMLElement;
declare const tapFlash: HTMLElement;
declare const multiplierDisplay: HTMLElement;
declare const finalScoreDisplay: HTMLElement;
declare const finalTapsDisplay: HTMLElement;
declare const tierBreakdown: HTMLElement;
declare const initialSlots: NodeListOf<Element>;
declare const arrowButtons: NodeListOf<Element>;
declare const submitButton: HTMLButtonElement;
declare const initialsSection: HTMLElement;
declare const menuFromScoreButton: HTMLButtonElement;
declare const personalBestMessage: HTMLElement;
declare const leaderboardList: HTMLElement;
declare const menuFromLeaderboardButton: HTMLElement;
declare function getCurrentMonthKey(): string;
declare function getMonthlyBest(): number;
declare function setMonthlyBest(newScore: number): void;
declare function hasSubmittedThisMonth(): boolean;
declare function markSubmittedThisMonth(): void;
declare function detectDevice(): void;
declare function initUserId(): void;
declare function loadInitials(): void;
declare function saveInitials(): void;
declare function hasSeenInstructions(): boolean;
declare function markInstructionsSeen(): void;
declare function showScreen(screen: HTMLElement): void;
declare function showScreenWithFade(screen: HTMLElement): void;
declare function showInstructions(): void;
declare function updateHeartsVisibility(): void;
declare function updateHeartsDisplay(): void;
declare function getMultiplier(): number;
declare function classifyPoint(remaining: number): {
    tierLabel: string;
    multiplier: number;
    points: number;
};
declare function updateTierScoreboard(): void;
declare function flashTierRow(tierLabel: string): void;
declare function resetGame(): void;
declare function updateGameplayBackground(): void;
declare function updateRingColor(): void;
declare function updateRingThickness(): void;
declare function updateRing(): void;
declare function updateDisplay(): void;
declare function gameLoop(currentTime: number): void;
declare function handleSuddenDeathLifeLost(): Promise<void>;
declare function handleTimerZero(): void;
declare function showReadySetGo(): Promise<void>;
declare function startReadySetGo(): Promise<void>;
declare function goToStartScreen(): void;
declare function startGame(): void;
declare function handleStartScreenTap(e: Event): void;
declare function handleGameplayTap(e: Event): void;
declare function triggerFlash(tier?: string): void;
declare function showCelebration(tier: 'PERFECT' | 'GREAT'): void;
declare function showTooEarly(): void;
declare function showDebt(amount: number, points: number, multiplier: number): void;
declare function animateFillUp(target: number): Promise<void>;
declare function updateMultiplierDisplay(multiplier: number): void;
declare function updateMaxDisplay(): void;
declare function handleSuddenDeathTap(): void;
declare function endGame(): void;
declare function showScoreScreen(): void;
declare function cycleInitialUp(index: number): void;
declare function cycleInitialDown(index: number): void;
declare function submitScore(): void;
declare function showLeaderboard(): void;
declare function goToMainMenu(): void;
//# sourceMappingURL=game.d.ts.map