declare let timeRemaining: number;
declare let maxTime: number;
declare let taps: number;
declare let score: number;
declare let isRunning: boolean;
declare let lastFrameTime: number;
declare let lives: number;
declare let isLocked: boolean;
declare let isCountingDown: boolean;
declare let isReadySetGo: boolean;
declare let isShrinking: boolean;
declare let perfects: number;
declare let greats: number;
declare let goods: number;
declare let fines: number;
declare let poors: number;
declare let bads: number;
declare const POINTS: {
    perfect: number;
    great: number;
    good: number;
    fine: number;
    poor: number;
    bad: number;
};
declare let gameMode: 'sudden-death' | 'one-tap';
declare let ringEnabled: boolean;
declare let bounceEnabled: boolean;
declare let currentInitials: string[];
declare let deviceType: 'desktop' | 'mobile';
declare let userId: string;
declare const instructionsPopup: HTMLElement;
declare const mainMenuScreen: HTMLElement;
declare const startScreen: HTMLElement;
declare const gameplayScreen: HTMLElement;
declare const gameoverScreen: HTMLElement;
declare const scoreScreen: HTMLElement;
declare const leaderboardScreen: HTMLElement;
declare const gotItButton: HTMLElement;
declare const startGameButton: HTMLElement;
declare const helpButton: HTMLElement;
declare const leaderboardButton: HTMLElement;
declare const modeToggle: HTMLElement;
declare const ringToggle: HTMLElement;
declare const bounceToggle: HTMLElement;
declare const startTimerRing: HTMLElement;
declare const startHearts: HTMLElement;
declare const startInstruction: HTMLElement;
declare const timerDisplay: HTMLElement;
declare const scoreDisplay: HTMLElement;
declare const timerRing: HTMLElement;
declare const gameplayHearts: HTMLElement;
declare const instruction: HTMLElement;
declare const countdown: HTMLElement;
declare const timerContainer: HTMLElement;
declare const maxDisplay: HTMLElement;
declare const lifeLost: HTMLElement;
declare const finalScoreDisplay: HTMLElement;
declare const finalTapsDisplay: HTMLElement;
declare const tierBreakdown: HTMLElement;
declare const initialSlots: NodeListOf<Element>;
declare const arrowButtons: NodeListOf<Element>;
declare const submitButton: HTMLButtonElement;
declare const initialsSection: HTMLElement;
declare const menuFromScoreButton: HTMLButtonElement;
declare const personalBestMessage: HTMLElement;
declare const leaderboardList: HTMLElement;
declare const menuFromLeaderboardButton: HTMLElement;
declare function getCurrentMonthKey(): string;
declare function getMonthlyBest(): number;
declare function setMonthlyBest(newScore: number): void;
declare function hasSubmittedThisMonth(): boolean;
declare function markSubmittedThisMonth(): void;
declare function detectDevice(): void;
declare function initUserId(): void;
declare function loadInitials(): void;
declare function saveInitials(): void;
declare function hasSeenInstructions(): boolean;
declare function markInstructionsSeen(): void;
declare function loadSettings(): void;
declare function saveSettings(): void;
declare function showScreen(screen: HTMLElement): void;
declare function showScreenWithFade(screen: HTMLElement): void;
declare function showInstructions(): void;
declare function updateRingVisibility(): void;
declare function updateHeartsVisibility(): void;
declare function updateHeartsDisplay(): void;
declare function updateToggleDisplays(): void;
declare function classifyPoint(remaining: number): void;
declare function resetGame(): void;
declare function updateRing(): void;
declare function updateDisplay(): void;
declare function gameLoop(currentTime: number): void;
declare function handleTimerZero(): void;
declare function startLockoutPeriod(): void;
declare function startReadySetGo(): void;
declare function startCountdown(): void;
declare function goToStartScreen(): void;
declare function startGame(): void;
declare function handleStartScreenTap(e: Event): void;
declare function handleGameplayTap(e: Event): void;
declare function getTierInfo(remaining: number): {
    label: string;
    points: number;
};
declare function showTooEarly(): void;
declare function showDebt(amount: number, tierLabel: string, points: number): void;
declare function animateFillUp(target: number): Promise<void>;
declare function updateMaxDisplay(): void;
declare function handleSuddenDeathTap(): void;
declare function handleOneTapTap(): void;
declare function endGame(): void;
declare function showScoreScreen(): void;
declare function cycleInitialUp(index: number): void;
declare function cycleInitialDown(index: number): void;
declare function submitScore(): void;
declare function showLeaderboard(): void;
declare function goToMainMenu(): void;
//# sourceMappingURL=game.d.ts.map